apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
#      - name: mail-service
#        image: "tsawler/mail:1.0.0"
#        resources:
#          limits:
#            memory: "128Mi"
#            cpu: "500m"
#        ports:
#          - containerPort: 80
      - name: broker-service
        image: "tsawler/broker:1.0.2"
        env:
          - name: RABBIT_URL
            value: "amqp://guest:guest@localhost"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 80
#      - name: authentication-service
#        image: "tsawler/authentication:1.0.0"
#        env:
#          - name: DSN
#            value: "host=localhost port=5432 user=postgres password=password dbname=users sslmode=disable timezone=UTC connect_timeout=5"
#        resources:
#          limits:
#            memory: "128Mi"
#            cpu: "500m"
#      - name: logger-service
#        image: "tsawler/logger:1.0.0"
#        resources:
#          limits:
#            memory: "128Mi"
#            cpu: "500m"
#        ports:
#          - containerPort: 80
      - name: rabbitmq
        image: "rabbitmq:3.9-alpine"
        ports:
          - containerPort: 5672
      - name: mailhog
        image: "mailhog/mailhog:latest"
        ports:
          - containerPort: 1025
      - name: mongo
        image: "mongo:4.2.17-bionic"
        env:
          - name: MONGO_INITDB_DATABASE
            value: "logs"
          - name: MONGO_INITDB_ROOT_USERNAME
            value: "admin"
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: "password"
        ports:
          - containerPort: 27017
      - name: postgres
        image: "postgres:14.0"
        env:
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "password"
          - name: "POSTGRES_DB"
            value: "users"
        ports:
          - containerPort: 5432

#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: myapp-svc
#spec:
#  type: NodePort
#  selector:
#    app: myapp
#  ports:
#  - port: 80
#    targetPort: 80
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: postgres
#spec:
#  clusterIP: None
#  ports:
#    - port: 5432
#---
#kind: Endpoints
#apiVersion: v1
#metadata:
#  name: postgres
#subsets:
#  - addresses:
#      - ip: 192.168.86.24
#    ports:
#      - port: 5432
#        name: postgres
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: mongo
#spec:
#  clusterIP: None
#  ports:
#    - port: 27017
#---
#kind: Endpoints
#apiVersion: v1
#metadata:
#  name: mongo
#subsets:
#  - addresses:
#      - ip: 192.168.86.24
#    ports:
#      - port: 27017
#        name: mongo
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: rabbitmq
#spec:
#  clusterIP: None
#  ports:
#    - port: 5672
#---
#kind: Endpoints
#apiVersion: v1
#metadata:
#  name: rabbitmq
#subsets:
#  - addresses:
#      - ip: 192.168.86.24
#    ports:
#      - port: 5672
#        name: rabbitmq

